### ISSUE TITLE
Проблема с дыркой в раздевалке на пляже

### ISSUE THREAD

**Issue by albedocodemonkey** [allanonHHS/HHS-on-RenPy#104]
При попытке заняться сексом вылетает ошибка.
[traceback.txt](https://github.com/allanonHHS/HHS-on-RenPy/files/103573/traceback.txt)

**Comment by allanonHHS** [comment]
Ох и намудохался я с этими "с".
Иди в файл beachChangeRoom и 193 строку заменяй на 
```python
                    show expression 'pic/locations/beach/changeRoom/no12c.jpg' at top as tempPic
```
