### ISSUE TITLE
Перевод денег в школу выдаёт ошибку.

### ISSUE THREAD

**Issue by albedocodemonkey** [allanonHHS/HHS-on-RenPy#105]
int() выдаёт ошибку, если попытаться внести, к примеру, '10.0'. Я предлагаю поменять int() на float() и добавить исключение.
```python
try:
    float(value)
except ValueError:
    print('Вы не ввели число, попробуйте еще раз')
```
Если очень хочется, то можно и хранить деньги в int, конечно, но их всё равно придётся конвертировать в float сначала.
```python
value = int(float(value))
```

[traceback.txt](https://github.com/allanonHHS/HHS-on-RenPy/files/103639/traceback.txt)

**Comment by allanonHHS** [comment]
Спасибо!
