### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'int' and 'instancemethod'

### ISSUE THREAD

**Issue by albedocodemonkey** [allanonHHS/HHS-on-RenPy#108]
Кажется, ты забыл добавить скобки в 31 строке к: 
```python
player.getBeauty() - char.getBeauty > 0
```
А должно быть:

```python
player.getBeauty() - char.getBeauty() > 0
```
По хорошему, имхо, в строке не помешали бы скобки, чтобы проще было читать код.

Ошибка вылетает, если попытаться выйти из раздевалки на пляже голой.

[traceback.txt](https://github.com/allanonHHS/HHS-on-RenPy/files/105503/traceback.txt)

**Comment by allanonHHS** [comment]
В 0.2.5 пофикшено уже
