### ISSUE TITLE
Собеседник перемещается/переодевается во время разговора.

### ISSUE THREAD

**Issue by ntcntl** [allanonHHS/HHS-on-RenPy#112]
сабж.
начинаешь диалог - он в форме, поговорил - уже в купальнике

**Comment by allanonHHS** [comment]
В общем время надо проматывать в конце, в зависимости от того, сколько потратили очков общения. Скажем, по 2 минуты за одно очко.

**Comment by NikAndrei** [comment]
так же препод перемещается на урок из любой локации в школе, говоришь с ним допустим в холле, а после общения он уже на уроке и можно провести с ним урок, а локация остается холл

**Comment by allanonHHS** [comment]
>так же препод перемещается на урок из любой локации в школе, говоришь с ним допустим в холле, а после общения он уже на уроке и можно провести с ним урок, а локация остается холл

Это другое.

>еще в эту же копилку, когда разговариваешь с человеком около 9 вечера, то перемещается в неизвестном направлении, возможно домой) но глюк в том что, остается окно с разговором из которого нельзя выйти

А вот это интересно. Должна оставаться одна кнопка - попрощаться... Кинь сейв плиз.

**Comment by NikAndrei** [comment]
уже переписал его(

**Comment by ntcntl** [comment]
> А вот это интересно. Должна оставаться одна кнопка - попрощаться... Кинь сейв плиз.

Неа, она тоже под условие попадала. Её нужно левее сдвинуть. А лучше сразу писать "Собеседник свалил" и кидать на курлок...

**Comment by ntcntl** [comment]
о! знаю. ща попробую написать...
