### ISSUE TITLE
Не праильное определение пола или косяк в тексте

### ISSUE THREAD

**Issue by NikAndrei** [allanonHHS/HHS-on-RenPy#113]
![3](https://cloud.githubusercontent.com/assets/16773284/12697458/edb8b11e-c794-11e5-9fa8-c4e3e54f2459.jpg)
![4](https://cloud.githubusercontent.com/assets/16773284/12697468/26a5aaa4-c795-11e5-954e-c60e53da283e.jpg)

![2](https://cloud.githubusercontent.com/assets/16773284/12696105/4bb2de16-c772-11e5-93ae-aaa0261dac73.jpg)
![1](https://cloud.githubusercontent.com/assets/16773284/12696104/4ba5fce6-c772-11e5-8888-b4e770ee5d49.png)

**Comment by allanonHHS** [comment]
Скорее всего это футы.
