### ISSUE TITLE
Ввести подарки в магазин и возможность их дарить.

### ISSUE THREAD

**Issue by allanonHHS** [allanonHHS/HHS-on-RenPy#19]
1. Подарки должны продаваться в магазине
2. Подарки - отдельный сабкласс от Item. У них должен быть пол(кому дарить), стоимость и параметры лояльности/коррупции/репутации, которые они меняют.
3. Дарить можно при взаимодействии с персонажем (Вместо карманов например).

**Comment by irvin-zamora** [comment]
Давай я попробую реализовать? Сделаю всю инфраструктуру, а сами подарки придумать сможешь ты.

**Comment by allanonHHS** [comment]
Попробуй.

**Comment by irvin-zamora** [comment]
Коррупция - это в смысле коррапшн?

**Comment by allanonHHS** [comment]
Она.

**Comment by allanonHHS** [comment]
Спасибо! Добавил несколько предметов, слегка подредактировал, всё работает.
