### ISSUE TITLE
Сделать статусы.

### ISSUE THREAD

**Issue by allanonHHS** [allanonHHS/HHS-on-RenPy#24]
У каждой локации есть возможные статусы (действия, которые можно в ней совершать)
В момент нахождения на локации НПС берут рандомный статус из локации.
Статусы отображаются при наведении на имя персонажа небольшой картинкой.
Статусы появляются в описании.
Некоторые статусы провоцируют миниэвент при попытке взаимодействия с учеником.
Некоторые статусы могут быть взяты только мальчиками, некоторые - девочками, для некоторых статусов необходима определённый параметр, например развратность или желание.

Предполагаемые статусы:
Все локации:
- ходьба (при этом статусе НПС сменит локацию)
- игра (Повысится fun)
- стоять (при этом статусе, ученик не сменит локацию в следующие 10 минут)

Все классы:
- учёба (повысится edu)

Туалеты:
- мыть руки
- писать (Миниэвент с посыланием ГГ куда подальше. Или нет.)

Бассейн, пляж:
- плавать
- загорать

**Comment by irvin-zamora** [comment]
Вопрос по поводу статусов, которые будут менять характеристики, к примеру:
> игра (Повысится fun)

Это будет статус с ивентом, в котором fun повысится. Или нужно сделать для класса статусов возможность задать post экшн на статусы, типа если персонаж взял этот экшн - повысить fun на 5, увеличить corr на 3 и т.п.?

**Comment by allanonHHS** [comment]
Второе. Взял статус - получил бонус. Но не больше какого то значения. Заиграть себя до 100 fun не получится.

**Comment by irvin-zamora** [comment]
Появляются доп. вопросы :)
1. Нужно ли задавать вероятность для статуса, или "игра", "стоять", "идти" будут иметь одинаковую вероятность выбора?
2. Связанный с 1-м - возможно ли, что зайдя на локацию, персонаж не выберет ни одного статуса?
3. Если нужна вероятность выбора статуса - она будет одинаковой и для учителей и для учеников?
4. Реализовал текстовую визуализацию статуса на экране *charInfoLeft*, а на каком экране нужна визуализация картинкой?

**Comment by allanonHHS** [comment]
1. Ты заложи эту возможность на всякий пожарный, но пока я планирую что из всех доступных будет выбираться любой.
2. Нет. Сделай дефолтный "идти"
3. Хороший вопрос. Я не знаю как ты реализуешь распределение статусов, но по идее некоторые статусы недоступны для учителей, а некоторые для учеников.
Во время уроков очевидно все ученики должны "учиться", а учителя "учить".
4. - В screen peopleTextList в textbutton x.name при hovered
- locationPeoplePicto, imagebutton, в hovered.
В charInfoLeft не надо пихать. В общем сделай отдельный скрин для показа статуса. Пока пусть текстом будет, я потом картинки добавлю.

**Comment by irvin-zamora** [comment]
Еще пара вопросов по ивентам. Я думаю впихнуть их вызов в
    label speak
но если сделать оттуда renpy.jump - мы потом не вернемся к разговору с персонажем, а просто вернемся на локацию. Плюс ивент должен срабатывать с какой-то вероятстью? И еще он сейчас постоянно срабатывает, т.е. персонаж взял статус на локации и при попытке с ним заговорить - постоянно получаешь ивент. Нужно ли сделать чтоб ивент срабатывал только 1 раз на статус?

**Comment by allanonHHS** [comment]
Эвент должен срабатывать всегда.
Вызов не надо впихивать в label speak, эвент должен срабатывать сразу, при старте взаимодействия.
Мы всегда можем вернуться к экрану взаимодействия через call screen show_stat.
Эвент пусть всегда срабатывает на статусе. В худшем случае, после эвента можно сделать принудительную смену статуса.

**Comment by allanonHHS** [comment]
Великолепно!
