### ISSUE TITLE
Сделать правдоподобную генерацию учеников.

### ISSUE THREAD

**Issue by allanonHHS** [allanonHHS/HHS-on-RenPy#3]
1. мальчиков должно быть 40%, фут - 10%, но минимум по 1 в каждый класс, девочек - 50%.
2. В каждом классе распределение мальчиков и девочек должно быть равномерно. Т.е. не должно быть только мальчаковых или только девчковых классов.
3. Интеллект - с вероятностью 10% он может быть меньше 20 или больше 80. Иначе от 30 до 70.
4. То же самое с волей. волевых и безвольных - мало. Остальные болтаются посередине.
5. Мальчиков не может быть больше 30, девочек - 40. Больше нету пиктограмм. Дублировать пиктограммы не надо.
6. Количество людей в классах должно быть одинаковым
7. Равномерного распределения не надо, но минимум по 2 человека разного пола должны быть в одном классе.

**Comment by irvin-zamora** [comment]
Займусь

**Comment by irvin-zamora** [comment]
По поводу интеллекта и воли:  ты хочешь чтобы из всех учеников было 5% гениев, 5% тупиц и 90 процентов середняков, или для каждого ученика выставлять интелект с такими вероятностями? В последнем случае может вообще не получится тупых или гениев. К примеру:
Intelligence:
	<20: 0 (0.0%)
	>80: 38 (76.0%)
	30-70: 12 (24.0%)
Will:
	<20: 1 (2.0%)
	>80: 37 (74.0%)
	30-70: 12 (24.0%)

И еще одни вопрос: у тебя отсутствует условие для интеллекта 20-30 и 70-80. Т.е. сейчас так:
1) либо меньше 20
2) либо больше 80
3) либо 30-70
Это так задумана или бага?

**Comment by allanonHHS** [comment]
10% что тупой. Не 5, а 10.
10% что умный
Для воли то же самое.
Насчёт 20-30 и 70-80 так и задумано.
