### ISSUE TITLE
Сделать секс систему. Примерно как в NewLife

### ISSUE THREAD

**Issue by allanonHHS** [allanonHHS/HHS-on-RenPy#31]
Сделать класс экшенов. Он содержит:
1. Ссылку на лэйбл этого экшена
2. Range Will
3. Range Lust
4. Range Corr
5. Range Loy
6. Cover одежды для которой этот экшн (опционально)
7. Cover одежды для которой этот экшн запрещён (нельзя трахаться в штанах. Я знаю, что можно, но нельзя будет.)
8. Имя экшена
9. Пол, который этот экшн может использовать (любой, мальчик, девочка, фута)
10. Пол для которого этот экшн предназначен  (любой, мальчик, девочка, фута)

Сама система:
1. Игроку выпадает список доступных экшенов
2. Он выбирает один из них, в функцию передаётся выбранный экшн
3. Функция подбирает экшн для партнёра, присваивает лейбл выбранного экшена переменной, дёргает лейбл экшена игрока.
4. Идёт экшн игрока, в конце дёргается экшн из переменной, которая была объявлена в функции.
5. См. пункт 1.

**Comment by Ekipogh** [comment]
Воу, вот это аппетиты. Сделайте просто ивенты.

**Comment by allanonHHS** [comment]
Интерактивненько получится. Система не настолько сложна, просто понадобится много экшенов, текста и картинок. Зато с каждым персонажем будет уникальный "опыт".

**Comment by allanonHHS** [comment]
Будет как в мастурбации. Одна картинка и разный текст к ней, в зависимости от состояния партнёров. Передумал делать это страшилище.
