### ISSUE TITLE
Изменить метод сравнения в stats_actions.

### ISSUE THREAD

**Issue by allanonHHS** [allanonHHS/HHS-on-RenPy#37]
Сейчас всегда сравнивается с максимально возможным значением. Например stats_actions={'fun': (1, 20)} увеличивает фан не выше 20.
Но при отрицательном изменении параметра, всё равно смотрится, чтобы он не был выше 20.
Например stats_actions={'fun': (-1, 20)} будет уменьшать фан вплоть до 0.
Хотелось бы, чтобы при {'fun': (-1, 20)}, 20 - стало минимально возможным значением.

**Comment by irvin-zamora** [comment]
Я поправлю этот и #38

**Comment by allanonHHS** [comment]
Спасибо тебе!
