### ISSUE TITLE
Преподаватели ведут уроки в пустых классах

### ISSUE THREAD

**Issue by anon12321** [allanonHHS/HHS-on-RenPy#46]
Иногда случается ситуация, когда 4 класса занимаются в классах-локациях + 1 класс в спортзале. Но занятия ведутся во всех 5 классах-локациях. Т.е. в каком-то классе-локации преподаватель ведёт занятие без учеников. Хорошо бы отправлять его на время урока в учительскую или ещё куда нибудь.

**Comment by allanonHHS** [comment]
Да, я знаю. Пока не приоритет, но пусть висит, пофикшу.
Обрати пожалуйста внимание на одежду учеников. С ней тоже по моему что то не так. Они всегда должны сейчас одеваться к месту.

**Comment by ntcntl** [comment]
Если быть точнее: у учителей в классе статус "Преподает" постоянный, т.е. остается даже на перемене.

**Comment by allanonHHS** [comment]
Угу, я видел. Я не уверен в чём точно проблема. По моему они просто не берут другой статус. Буду посмотреть.

**Comment by allanonHHS** [comment]
Пофиксил. Они действительно просто не перемещались.

**Comment by ntcntl** [comment]
Так, что бы они не вели занятие вроде сделал, только они теперь уйти из класса не могут))) сейчас еще посмотрю...

**Comment by ntcntl** [comment]
в  ```otherFunctions.rpy``` исправить в строках: ```295, 300, 305, 310, 315, 320``` нолики из условия, на единицы. А то видимо если учитель на начала урока в классе, то не уходит в учительскую...
