### ISSUE TITLE
Ошибки при старте разговора:

### ISSUE THREAD

**Issue by ntcntl** [allanonHHS/HHS-on-RenPy#50]
1. Если стартовать разговор через список людей (в левой части экрана), то чаще всего окно диалога открывается не на текущей локации (при этом кнопки локации также активны.
2. Если через "Глаз" справа вывести пиктограммы присутствующих и выбрать кого либо - сразу стартует "разговор" (кроме новых событий привязанных к "статусу"), при этом "Очки общения" уходят в минус.

**Comment by allanonHHS** [comment]
1. Вообще ни разу не воспроизвелось... Сохранись и приатач сэйв пожалуйста.
2. Аналогично. Не воспроизводится.

Какой версией Renpy собираешь? Я счас пользуюсь 6.99.1.329.

**Comment by ntcntl** [comment]
[url=https://yadi.sk/d/ErcrbEQ5mxqij]Сохранка[/url]
Нахожусь на улице у дома, жму на любого студента и оказываюсь на пляже.
[url=http://uploads.ru/ktZaF.png][img]http://s3.uploads.ru/t/ktZaF.png[/img][/url]

[url=https://yadi.sk/d/CDljNQxDmxrZy]Сохранка 2[/url]
Тут же отрыл портреты: жму на любой - стартует диалог, очки общения уходят в минус.
Версия 6.99.8.959 - но на более ранних был такой же прикол...

**Comment by allanonHHS** [comment]
Я выложил в темке то, чем я собираю. Очень странное поведение. Не может же быть так, что у меня всё работает, а у тебя нет?

**Comment by ntcntl** [comment]
Скачал Renpy 6.99.1 - работает без бага.
Значит он появляется в более поздних версиях (точно есть в 6.99.6 и 6.99.8).

**Comment by allanonHHS** [comment]
Это проблема совместимости. В будущем надо будет перепилить на последний ренпай, но очевидно, что пока не приоритет.
