### ISSUE TITLE
Сделать снос статусов с локации по одному.

### ISSUE THREAD

**Issue by allanonHHS** [allanonHHS/HHS-on-RenPy#51]
Собственно вот этот код:
``` python
def removeStatus(self, status):
    for x in self.__statuses:
        if x == status:
            self.__statuses.remove(x)
```

Не пашет так, как задумано. А задумано, что он может снести добавленный статус с локации.

**Comment by anon12321** [comment]
**Не по теме задачи**

Чтобы не билось форматирование кода в тексте issue, можно ставить перед и после тройной backtick (`)

Тогда будет так:
``` python
def removeStatus(self, status):
    for x in self.__statuses:
        if x == status:
            self.__statuses.remove(x)
```

[Тут](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) подробнее.

**Comment by allanonHHS** [comment]
Всё, теперь работает! Спасибо!
