### ISSUE TITLE
Разбить файл randomEvents.rpy на несколько

### ISSUE THREAD

**Issue by anon12321** [allanonHHS/HHS-on-RenPy#53]
`randomEvents.rpy` имеет размер почти 400 килобайт. Может быть, есть смысл разбить его на несколько файлов? Например, для каждой локации (улица, пляж и т.п.) по отдельному файлу.

**Comment by allanonHHS** [comment]
Побью. Завтра вечером. Я просто не думал вначале, что в игре столько эвентов.
