### ISSUE TITLE
Сделать совместимость с новой версией RenPy

### ISSUE THREAD

**Issue by allanonHHS** [allanonHHS/HHS-on-RenPy#57]
Игра глючит на новых версиях RenPy.
Из известного: Пихается скрин beach в iteraction.

**Comment by ntcntl** [comment]
Нашел где был баг.
Сейчас запуллю ;)

**Comment by allanonHHS** [comment]
Я проверю дома и закрою тогда.

**Comment by allanonHHS** [comment]
Вроде не воспроизводится.
