### ISSUE TITLE
При students > 70, отваливается геренерация при попытке попнуть из пустого листа.

### ISSUE THREAD

**Issue by allanonHHS** [allanonHHS/HHS-on-RenPy#62]
While running game code:
  File "game/generation.rpy", line 345, in script
    python:
  File "game/generation.rpy", line 407, in <module>
    _studs = generate_students(students, 5)
  File "game/generation.rpy", line 99, in generate_students
    s = students_pool.pop(rand(0, len(students_pool)-1))
IndexError: pop from empty list

**Comment by irvin-zamora** [comment]
У меня еще падает из-за нехватки картинок учеников, где можно скачать последний пак картинок?

**Comment by allanonHHS** [comment]
Отключи пока вырезание дубликатов картинок картинки. Я просто проверял, что будет если 100 учеников в школе и оно упало.
Отключается при комменте 53 строки в generation.rpy
picto_list.remove(picto)

**Comment by irvin-zamora** [comment]
Ага, нашел. Проблема в том, что количество мальчиков и девочек при генерации ограничивалось еще и количеством картинок для них:
```
girls = min(rand(round(students_number*0.45), round(students_number*0.55)),
                  len(picto_f))
boys = min(len(picto_m), students_number-futas-girls)
```
Отключил это ограничение, но теперь учти, что придется сделать картинок с запасом, т.к. количество девочек и мальчиков не фиксировано строго.

**Comment by allanonHHS** [comment]
Ясно, если буду сильно увеличивать школу, сделаю больше. Просто надо потестить, насколько всё будет тормозить при большем количестве учащихся.

**Comment by allanonHHS** [comment]
Неа. Не в этом проблема была.
'''python
            girls_l.pop(rand(0, len(boys_l)-1)).inClass = i
            girls_l.pop(rand(0, len(boys_l)-1)).inClass = i
'''
надо было так:
'''python
            girls_l.pop(rand(0, len(girls_l)-1)).inClass = i
            girls_l.pop(rand(0, len(girls_l)-1)).inClass = i
'''

**Comment by irvin-zamora** [comment]
Точно, это еще одна бага. Но проблема с картинками так же существует.
