### ISSUE TITLE
Более универсальная работа статусов.

### ISSUE THREAD

**Issue by ntcntl** [allanonHHS/HHS-on-RenPy#63]
Сейчас статус вызывает либо эвент, либо окно диалога.
Предлагаю диалог оформить так же в качестве эвента. Что это даст:
+ более универсальная обработка
+ для статусов типа "плавает" и т.п. появится возможность выбора дозвалась/не дозвалась...

Если это имеет смысл то в течении дня думаю могу сделать ;)

**Comment by allanonHHS** [comment]
Это всё можно сделать и сейчас, просто сделать выход из эвента не через $move(curloc), а через     
call screen show_stat. И будет возможность дозвался/не дозвался.
Просто пока не до этого.
