### ISSUE TITLE
Неправильное отображение имени в 187 строке qwestMustangovich.rpy

### ISSUE THREAD

**Issue by NikAndrei** [allanonHHS/HHS-on-RenPy#67]
Не знаю может уже сообщалось но мельком посмотрел не заметил сообщений о них и еще не знаю куда лучше писать об ошибках:
1. Описание локации у входа в школу не соответствует действительности, там написано что "Вроде как там раньше стоял сарай, но он давным давно рухнул, и теперь земля пустует. Библиотеку что ли там построить?", но здание библиотеки уже стоит.
2. Ивент с учителем Ахмедом, в тексте с ученицей после акта игрок обращается к ней "("Тут не то имя" похоже оно берется от первой ученицы с которой начинается сам ивент) , ты ведёшь себя нормально, сегодня был обычный день, устала ты потому, что сегодня был кросс на 5 км последним уроком. Уяснила?".  В 187 строке обращаемся к первой ученице player.say '[st1.fname],

**Comment by allanonHHS** [comment]
1. Не стоит. Это заглушка для разработчика. Если зайти в компьютер, то видно, что она не построена. Если её действительно построить, то должно заработать. Х
2. Спасибо, поправлю следующим коммитом.
