### ISSUE TITLE
Не открывается клуб чирлидеров

### ISSUE THREAD

**Issue by NikAndrei** [allanonHHS/HHS-on-RenPy#70]
Посмотрел по коду Вы не изменяете переменную is_cherleaderClub в конце общения.
В файле rEventsClass2.rpy

И там же пока не разобрался с кодом возможно нужно этим студенткам присвоить клуб

**Comment by NikAndrei** [comment]
попробовал изменить, вроде получилось добавил код между строками, с ренпи пока только разбираюсь, если не правильно, ну что ж))
28 строка    'В вашем школьном компьютере появилась возможность открыть клуб черлидеров.'
    python:
        global is_cherleaderClub
        st1.club = 'cherleader'
        st2.club = 'cherleader'
        is_cherleaderClub = 1    
    
29 строка    $ move(curloc)

**Comment by NikAndrei** [comment]
я еще не настроил гит, вся надежда на тебя и я не 100% уверен в коде, т.к. с ренпи не работал ни разу, да и не знаю пока логики игры, это было чисто для пробы сработает или нет, да и у тебя узнать правильно ли написал

**Comment by allanonHHS** [comment]
В теории правильно. Этот код должен сработать, если ты запихнёшь его в эвент.

**Comment by NikAndrei** [comment]
теперь понятно, я то у себя это уже сделал, теперь когда у вас будет время подправьте
