### ISSUE TITLE
Сброс статуса после просмотра

### ISSUE THREAD

**Issue by ntcntl** [allanonHHS/HHS-on-RenPy#71]
Некоторые статусы с ивентами активны дольше, чем занимает время их просмотр.
Так, к примеру, при статусе "копошится" во время урока его можно успеть активировать 2-3 раза и получить статы повторно.

З.Ы. ![Баг](https://github.com/allanonHHS/HHS-on-RenPy/issues/46) с преподаванием в пустых классах всё еще активен.

**Comment by allanonHHS** [comment]
Проблема не в этом, а в том, что желание не сбрасывается. Буду смотреть.

**Comment by allanonHHS** [comment]
Прям критикал бага была, нашёл, пофиксил.

**Comment by allanonHHS** [comment]
З.Ы. Баг с преподаванием в пустых классах всё еще активен.
Хер с ними пока. Так сходу не сделаю решение.
