### ISSUE TITLE
Парни в женском туалете.

### ISSUE THREAD

**Issue by ntcntl** [allanonHHS/HHS-on-RenPy#72]
Причем они там попадаются сразу с начала новой игры - т.е. отнести на счет разврата не получается.

Кстати, в связи с тем что в раздевалке появляются парни, в т.ч. со статусом "переодевается", предлагаю убрать последние предложения из описание локации (я про "кто знает, что там в соседнем отделении?")

**Comment by NikAndrei** [comment]
Тоже их видел в туалете в начале игры, думал можно отругать или наказать, но ничего такого не было

**Comment by allanonHHS** [comment]
Пофиксил. Теперь до 20 разврата не должны появляться, потом могут и иногда будут подглядывать.

**Comment by NikAndrei** [comment]
Посмотри еще и девушки в мужском туалете, не успел написать

**Comment by allanonHHS** [comment]
>Посмотри еще и девушки в мужском туалете, не успел написать

Это очевидно, так как проверки не было вообще никакой.
