### ISSUE TITLE
Обработка "сексуальности" одежды

### ISSUE THREAD

**Issue by ntcntl** [allanonHHS/HHS-on-RenPy#75]
1) Пиджак с вырезом + короткая юбка для собеседников оказываются более сексуальными чем бикини.
2) При "Вашему собеседнику неловко..." очки действий снимаются не за использование афродизиака/подарка, а при открытии окна их выбора (даже если передумать).

**Comment by allanonHHS** [comment]
1) Поднял сексуальность бикини.
2) Пофиксил. Теперь реакция считается только при клике на персонажа.

**Comment by ntcntl** [comment]
Может стоит с ней поступить наоборот - присвоить максимальный уровень голому телу, а одеждой минусовать? (ну разве что кроме колготок и бдсм)

**Comment by allanonHHS** [comment]
Да хз. Пока не горит. Взаимодействие с учениками вообще можно пока выключить, никакой полезной нагрузки это не несёт. Потом буду думать что с одеждой. Сейчас она только в паре эвентов проверяется.
