### ISSUE TITLE
Сброс листов подсвечивающихся/интро/афродизиака

### ISSUE THREAD

**Issue by ntcntl** [allanonHHS/HHS-on-RenPy#76]
При сохранении/загрузке без перезапуска проекта всё работает нормально. Если же игру полностью закрыть и запустить заново, то при загрузке получаются обнуленными как минимум:
```
    highlightP = [] # лист подсвечивающихся на локации
    aphroUsedArr = [] #лист тех, на ком юзался афродизиак
    teacher_intro = [] #лист просмотренных интро
```

**Comment by NikAndrei** [comment]
teacher_intro = [] #лист просмотренных интро
По этому поводу то же хотел написать, что постоянно приходится с ними знакомится

**Comment by allanonHHS** [comment]
Посмотри, не происходит ли это после презагрузки. По моему я знаю, в чём проблема.

**Comment by NikAndrei** [comment]
ntcntl, написал же что при перезапуске игры они обнуляются

**Comment by allanonHHS** [comment]
Ага, ну это просто решается.

**Comment by ntcntl** [comment]
> Вы меня простите, просто завал на работе, я сюда заглядываю периодически, но туплю.
Ничё, бывает... Я сам только немного отошел от перехода с работы на ставку, к работе на полторы еще и в смежных отделах...
P.S. за флуд извиняюсь ;)
