### ISSUE TITLE
Неправильное имя в ивенте про 4 класс

### ISSUE THREAD

**Issue by NikAndrei** [allanonHHS/HHS-on-RenPy#80]
Тут подставляется имя учительницы.
Строка 204 '[st1.name] сидит на уроке и внимательно слушает, что там вещает сегодня преподаватель математики. Вроде бы придраться не к чему. Разве что вас терзают сомнения, не забыла ли она сегодня дома трусики...'

**Comment by allanonHHS** [comment]
Наверняка не всегда. Просто учительница была одной из вероятностей. Пофиксил.
