### ISSUE TITLE
Квест на камеру

### ISSUE THREAD

**Issue by NikAndrei** [allanonHHS/HHS-on-RenPy#86]
Проверьте пожалуйста вызов квеста на камеру, походу он не вызывается. Я за эти дни теста ниразу его не видел

**Comment by allanonHHS** [comment]
А ты зайди в 4 класс, и посмотри, есть он там или нет.
Ты можешь открыть консоль и написать show pomogator, тебе вывалится весь список эвентов локации доступных для игры. Возможно недостаточно развратности школы.
