### ISSUE TITLE
Женский туалет. Курение. Не та картинка

### ISSUE THREAD

**Issue by NikAndrei** [allanonHHS/HHS-on-RenPy#87]
Видимо при переносе не обрати внимание, ты указал не ту картинку. Предположу, что должно быть так
стр61     show expression 'pic/locations/school/wcf/no%d.jpg' %rand(6,9) at right as tempPic

**Comment by allanonHHS** [comment]
Нет. Просто пак картинок автоматически устарел.

**Comment by NikAndrei** [comment]
А новый предвидится?

**Comment by allanonHHS** [comment]
Да. Мб вечером. выложу апдейт для туалета.
