### ISSUE TITLE
Учителя. Нельзя поговорить с учителем.

### ISSUE THREAD

**Issue by NikAndrei** [allanonHHS/HHS-on-RenPy#88]
Нельзя поговорить с учителями которые находится в учительской во время занятий, походу они думают, что еще на уроке

**Comment by irvin-zamora** [comment]
Похоже с учителями слишком много багов, Allanon, может попробовать выделить их в отдельный класс и перенести всю логику учительского расписания внутри него?

**Comment by allanonHHS** [comment]
Да нет. Просто проверку надо другую. Там по времени, а по хорошему надо проверять на статус. И вроде не так уж и много с ними багов?

**Comment by NikAndrei** [comment]
Ну пока только это заметил

**Comment by ntcntl** [comment]
Файл Interaction.rpy, строка 246. Заменить на:
```if interactionObj.locationStatus.name not in ['Занимается', 'Преподаёт'] :```

**Comment by allanonHHS** [comment]
>Файл Interaction.rpy, строка 246. Заменить на:
>if interactionObj.locationStatus.name not in ['Занимается', 'Преподаёт'] :

Немного по другому. Лучше не использовать настоящие названия, а дёрнуть имена из объекта. Иначе если я захочу переименовать Преподаёт в "проводит урок", мне придётся по всему коду искать, где я это указал.

**Comment by ntcntl** [comment]
Ну а к примеру 'Занимается' - это несколько разных статусов и тогда их все нужно указывать... Или я что-то не так понял?

**Comment by ntcntl** [comment]
Тогда может проверять не статус, а локацию, типа:
```if lt() <= 0 or getLoc(curloc) not in classrooms:```

**Comment by allanonHHS** [comment]
>Тогда может проверять не статус, а локацию
Неправильно. Логически неправильно. Ты не можешь вызвать к себе учителя только по одной причине - он занят преподаванием. Хз что там дальше навертится, где они там преподавать будут.
>Ну а к примеру 'Занимается' - это несколько разных статусов и тогда их все нужно указывать... Или я что-то не так понял?
А какая тебе разница, писать статусы по русски, или использовать status.name?

**Comment by ntcntl** [comment]
тогда наверно лучше в status_events.rpy создать переменную со списком статусов без разговора (там ее в случае чего менять проще)
```
not_speak_status = [learn_low_status, learn_mid_status, learn_high_status, learn_lust_status, teach_status]
```
и тогда получаем условие:
```
if interactionObj.locationStatus not in not_speak_status:
```
