### ISSUE TITLE
Список людей со статусами.

### ISSUE THREAD

**Issue by NikAndrei** [allanonHHS/HHS-on-RenPy#89]
Что то его глючит, текст моргает то зеленым то белым если мышкой поводить по нему, плюс еще заметил, что он иногда полностью зеленым становится

**Comment by NikAndrei** [comment]
Еще хочу предложить, перенести на нас какие нибудь ивенты для переноса, что бы у тебя было время для допиливания и исправления. Готов взяться попробовать, что нибудь легкое, так посмотреть как получится

**Comment by allanonHHS** [comment]
А вот это дело хорошее. Перенеси спортзал. Его эвенты в куспе находятся в gym_no, gym_low, gym_mid.
По поводу листа с учениками - хз. По идее последний человек с которым ты разговаривал, будет зелёным. Не замечал с ним особых глюков.

**Comment by NikAndrei** [comment]
тогда вопрос про нумерацию ивентов как ты ее делаешь?
event_loc_wcf_10_no10:
event_loc_wcf_0_no1:

что означает 10 после wcf?

**Comment by allanonHHS** [comment]
Смысл имени лейбла такой:
event_[айди локации]_[Необходимый уровень разврата]_[Уникальный набор символов]

айди локации - ну ты понял, loc_wcf например
Необходимый уровень разврата - ну для "подрочить" около 30, для секса - 50, я где то писал подробне примерную раскладку.
Уникальный набор символов - тут неважно что ты напишешь, просто чтобы отличать одни эвенты от других.

Сделаешь такой лейбл, игра автоматически его добавит на локацию как возможный эвент.
