### ISSUE TITLE
Баг с вызванным учеником

### ISSUE THREAD

**Issue by ntcntl** [allanonHHS/HHS-on-RenPy#90]
Фикс бага #74 - добавить в функцию def addPeopleLocations(): условие
```
        if lt() < 0 and callup != dummy: 
            global callup 
            callup = dummy # убрать из кабинета в неробочее время
```
т.к. всё еще воспроизводится

**Comment by allanonHHS** [comment]
У меня не воспроизводится. Кинь сейв.

**Comment by ntcntl** [comment]
[saves.zip](https://github.com/allanonHHS/HHS-on-RenPy/files/99021/saves.zip)

**Comment by allanonHHS** [comment]
Это другой баг.

**Comment by ntcntl** [comment]
ну фикс что я написал работает, как буду дома может залью...

**Comment by allanonHHS** [comment]
Не надо. По другому там надо.... Тут глубже баг. Связан с тем, что при вызове ученик действительно перемещается в кабинет. Но потом уходит, а callup не чистится. И чистить его надо в том месте, когда ученик уходит, а не абы где.

**Comment by ntcntl** [comment]
не совсем так, "уходит" он аж в 21 час, когда все убираются с локаций на ночь. Можно конечно чистить callup там, но по-моему лучше сбросить раньше и тот сам уйдет.

**Comment by ntcntl** [comment]
Кстати еще 1 баг с вызванным учеником. 
[1-2-LT1.zip](https://github.com/allanonHHS/HHS-on-RenPy/files/99084/1-2-LT1.zip)

Выгоняем ==> портрет исчезает, а в списке локации он еще есть. Можно попробовать выгнать повторно и соответственно словить баг.
Есть 2 варианта фикса:
1 - перемещать при выдворении в коридор
2 - блокировать кнопку "выгнать" если нет в callup
Что лучше?
