### ISSUE TITLE
Голосование на мед.кабинет / библиотеку

### ISSUE THREAD

**Issue by ntcntl** [allanonHHS/HHS-on-RenPy#91]
Если предложение поддерживают учителя, то в голосовании появляется голос мед.сестры / библиотекаря.
В смысле сразу же, в текущем голосовании на постройку своего кабинета. Причем вплоть до вето.
Типа все согласились на мед.кабинет, а гонореевна наложила вето.

**Comment by NikAndrei** [comment]
там еще после приобретения мед кабенета в компьютере он отображается как не купленный, ну это было в прошлой версии, на этой я еще не смотрел

**Comment by allanonHHS** [comment]
Да, знаю. Это чистая косметика, на самом деле голосование проходит нормально.

**Comment by NikAndrei** [comment]
allanonHHS, на форум загляни, я тебе туда написал. Блин ну почему нету чата..

**Comment by antage** [comment]
Для чата можно такую штуку использовать - https://gitter.im/
Но это, конечно, если @allanonHHS захочет через чат общаться.

**Comment by allanonHHS** [comment]
https://gitter.im/allanonHHS/HHS-on-RenPy
Тут

**Comment by ntcntl** [comment]
> Да, знаю. Это чистая косметика, на самом деле голосование проходит нормально.

Ну кстати при варианте 3 за / 3 против библиотека не покупается... Или это так и должно? (просто раньше помню при равенстве вроде перевешивал "за")

**Comment by NikAndrei** [comment]
неа, против, в прошлых так и было

**Comment by allanonHHS** [comment]
>Или это так и должно? (просто раньше помню при равенстве вроде перевешивал "за")

Ну пока так и должно. if voteYes > voteNo and voteVeto == 0:

**Comment by ntcntl** [comment]
в связи с отключением медсестры/библиотекаря - неактуально.
